Modifying script

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,222 +1,215 @@
 version: 2.1
 
-# orbs:
-#     slack: circleci/slack@4.9.4
-# commands:
-#   destroy_environment:
-#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
-#     parameters:
-#       workflow_id:
-#         type: string
-#         default: ${CIRCLE_WORKFLOW_ID:0:7}
-#     steps:
-#       - run:
-#           name: Destroy environments
-#           when: on_fail
-#           command: |
-#             echo "Destroying environment: <<parameters.workflow_id>> "
-#             aws cloudformation delete-stack --stack-name udapeople-backend-prod-<<parameters.workflow_id>>
-#             aws s3 rm s3://udapeople-prod-<<parameters.workflow_id>> --recursive
-#             aws cloudformation delete-stack --stack-name udapeople-frontend-prod-<<parameters.workflow_id>>
- # ---------------------------------------------------------------------------- #
- #                              Slack Notifications                             #
- # ---------------------------------------------------------------------------- #
+orbs: 
+  node: circleci/node@5.0.2
+  slack: circleci/slack@4.9.4
 
-  # notify_on_failure:
-  #   steps:
-  #     - slack/notify:
-  #         channel: C033R6TGLDV  # Slack channel to post to
-  #         event: fail
-  #         template: basic_fail_1
-   
+commands:
+  notify_on_failure:
+    steps:
+      - slack/notify:
+          channel: D033Z58UL4E
+          template: basic_fail_1
 
-# ---------------------------------------------------------------------------- #
-#                                 Jobs Section                                 #
-# ---------------------------------------------------------------------------- #
-
+  install_awscli:
+    description: "Installs AWS_CLI"
+    steps:
+      - run: 
+          name: "Install AWS CLI"
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+  install_ansible:
+    description: "Installs Ansible on Ubuntu images"
+    steps:
+      - run: 
+          name: "Install Ansible"
+          command: |
+            sudo apt update
+            sudo apt install software-properties-common -y
+            sudo add-apt-repository --yes --update ppa:ansible/ansible
+            sudo apt install ansible -y
+  
+  install_nodejs:
+    description: "This command installs NodeJS on the docker image"
+    steps:
+      - run:
+          name: "Installing node js"
+          command: |
+            curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
+            sudo apt install -y nodejs
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      Workflow_ID:
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
+            aws s3 rm s3://udapeople-<< parameters.Workflow_ID >> --recursive
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
+            
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      Workflow_ID:
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
+    steps:
+      - run:
+          name: Revert migrations
+          when: on_fail
+          command: |
+            SUCCESS=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/migration-<< parameters.Workflow_ID >>)
+            if(( $SUCCESS==1 )); 
+            then
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
+            fi
+            
 jobs:
   build-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [frontend-depnd]
       - run:
-          name: Install prerequsites
-          command: |            
-            sudo apt -y install jq tar gzip git curl
-      - run:
-          name: Frontend Build
+          name: Build front-end
           command: |
             cd frontend
-            npm i
+            npm install
             npm run build
       - save_cache:
-          key: v1-frontend-build
-          paths:
-            - ~/project/frontend/node_modules
-      # - notify_on_failure
+          paths: [frontend/node_modules]
+          key: frontend-depnd
+      - notify_on_failure
 
   build-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-depnd]
       - run:
-          name: Install prerequsites
-          command: |
-            sudo apt -y install jq tar gzip git curl
-      - run:
-          name: Backend build
+          name: Back-end build
           command: |
             cd backend
-            npm i
-            npm run build
+            npm install
+            npm run build 
       - save_cache:
-          key: v1-backend-build
-          paths:
-            - ~/project/backend/node_modules
-    
-      # - notify_on_failure
+          paths: [backend/node_modules]
+          key: backend-depnd
+      - notify_on_failure
 
   test-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-depnd]
       - run:
-          name: frontend test
+          name: Frontend unit test
           command: |
             cd frontend
-            npm i
-            npm run test  
-      # - notify_on_failure
-    
+            npm install
+            npm test 
   test-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-depnd]
       - run:
-          name: backend test
+          name: Backend unit test
           command: |
             cd backend
             npm install
             npm test
-      # - notify_on_failure
+      - notify_on_failure
 
   scan-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-depnd]
       - run:
-          name: frontend scan
+          name: Frontend scan
           command: |
             cd frontend
+            npm install
+            npm audit fix --audit-level=critical --force
+            npm audit fix --audit-level=critical --force
             npm audit --audit-level=critical
-      # - notify_on_failure
+      - notify_on_failure
 
   scan-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-depnd]
       - run:
-          name: backend scan
+          name: Backend scan
           command: |
             cd backend
             npm install
             npm audit fix --audit-level=critical --force
+            npm audit fix --audit-level=critical --force
             npm audit --audit-level=critical
-      # - notify_on_failure
-
-  deploy_backend_infrastructure:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Deploy the backend infrastructure using cloudformation
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              --parameter-overrides ID="prod-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --stack-name udapeople-backend-prod-${CIRCLE_WORKFLOW_ID:0:7}
-      - run:
-          name: Save backend URL and IP (for ansible)
-          command: |
-            BACKEND_AWS_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-prod-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            echo "http://$BACKEND_AWS_PUBLIC_IP:3030" >> .circleci/outputs/backend_url.txt
-            echo "[all]" >> .circleci/ansible/inventory.txt
-            echo "$BACKEND_AWS_PUBLIC_IP" >> .circleci/ansible/inventory.txt
-            cat .circleci/outputs/backend_url.txt
-      - run: yum -y install tar gzip
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/outputs/backend_url.txt
-            - project/.circleci/ansible/inventory.txt
-
-      # - destroy_environment
-          
-
+      - notify_on_failure
+      
   deploy-infrastructure:
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
-
       - run:
-          name: Install prerequsites
-          command: |
-            yum -y install tar gzip jq git
+          name: "installing tar and gzip"
+          command: yum install -y tar gzip
       - run:
-          name: Ensure backend infrastructure exists
+          name: create backend infrastructure
           command: |
-            # build-backend:
             aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              --tags project=udapeople \
-              --stack-name "backend-infrastructure-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
+            --template-file .circleci/files/backend.yml \
+            --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+            --tags project=project3
       - run:
-          name: Add backend ip to ansible inventory
+          name: creating frontend infrastructure
           command: |
-            BACKEND_IP=`aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query "Reservations[*].Instances[*].[PublicDnsName]" \
-              --output text | tr -d '\n'`
+            aws cloudformation deploy \
+            --template-file .circleci/files/frontend.yml \
+            --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+            --tags project=project3
+      - run:
+          name: Add backend EC2 IP to ansible inventory file
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
             echo $BACKEND_IP >> .circleci/ansible/inventory.txt
             cat .circleci/ansible/inventory.txt
-           
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-
-      - run:
-          name: Ensure frontend infrastructure exist
-          command: |
-            # build-frontend:
-            aws cloudformation deploy \
-            --template-file .circleci/files/frontend.yml \
-            --tags project=udapeople \
-            --stack-name "frontend-infrastructure-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
-      
-      # - destroy-environment 
-
+      - destroy-environment
 
   configure-infrastructure:
     docker:
@@ -235,29 +228,240 @@ jobs:
             cd .circleci/ansible
             cat inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
-      # - destroy-environment  
-  
+      - destroy-environment
+
+  run-migrations:
+    docker:
+      - image: cimg/node:13.8.0
+    steps:
+      - checkout
+      - install_awscli
+      - restore_cache:
+          keys: [backend-depnd]
+      - run:
+          name: Run migrations
+          command: |
+              cd backend
+              npm i
+              npm run build
+              npm run migrations >> migrations_dump.txt 
+      - run:
+          name: Send migration results to Kvdb.io
+          command: |
+            cd backend
+            if grep -q "No migrations are pending" migrations_dump.txt
+            then
+              curl -d '1' https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} 
+            fi
+      - destroy-environment
+      - revert-migrations
+
+  deploy-frontend:
+    docker:
+      - image: cimg/base:2022.04 
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - restore_cache:
+          keys: [backend-depnd]
+      - run:
+          name: Install dependencies
+          command: |
+            cd frontend
+            npm install
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
+            echo "API_URL=http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      - destroy-environment
+      - revert-migrations
+                    
+  deploy-backend:
+    docker:
+      - image: cimg/base:2022.04
+    steps:
+      - checkout
+      - install_awscli
+      - install_ansible
+      - install_nodejs
+      - add_ssh_keys:
+          fingerprints: ["8a:d6:c1:de:00:85:c5:9b:b4:d5:90:49:0c:b8:99:6a"]
+      - attach_workspace:
+          at: ~/
+      - restore_cache:
+          keys: [backend-depnd]
+      - run:
+          name: Install dependencies
+          command: |
+            cd backend
+            npm install
+      - run:
+          name: package backend
+          command: |
+            cd backend
+            npm i
+            npm run build
+            cd ../
+            tar -czf artifact.tar.gz backend
+            cp artifact.tar.gz .circleci/ansible/roles/deploy/tasks/files
+      - run:
+          name: Deploy backend
+          command: |
+            export TYPEORM_MIGRATIONS_DIR=.migrations
+            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+            export TYPEORM_MIGRATIONS=./migrations/*.ts
+            cd .circleci/ansible
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      - destroy-environment
+      - revert-migrations
+
+  smoke-test:
+    docker:
+      - image: cimg/base:2022.04
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
+            export API_URL=http://${BACKEND_IP}:3030
+            if curl -s ${API_URL}/api/status | grep "ok"
+            then 
+                exit 0
+            else
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_TEST=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_TEST | grep "Welcome"
+            then 
+                exit 0
+            else
+                exit 1
+            fi
+      - destroy-environment
+      - revert-migrations
+
+
+  cloudfront-update:
+    docker:
+      - image: cimg/base:2022.04
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+           name: deployment 
+           command: |
+            export WorkflowID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text) 
+            echo $workflowID >> ./workflow.txt
+            cat ./workflow.txt
+    # curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '$WorkflowID'
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --stack-name InitialStack \
+            --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --tags project=udapeople
+    
+      # - destroy-environment
+      # - revert-migrations
+
+# cleanup:
+#     docker:
+#       # Docker image here
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Get old stack workflow id
+#           command: |
+#             # your code here
+#             export OldWorkflowID="the id here"
+#             export STACKS=[] #put the list of stacks here
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#             then
+#               # your code here
+#             fi
+            
+  notify_on_success:
+    docker:
+      - image: cimg/base:2022.04
+    steps:
+      - slack/notify:
+          channel: D033Z58UL4E
+          event: pass
+          template: success_tagged_deploy_1
+      
 
 workflows:
-   default:
-      jobs:
-       - build-frontend
-       - build-backend
-       - test-frontend:
-          requires: [build-frontend]
-       - test-backend:
-          requires: [build-backend]
-       - scan-backend:
-          requires: [build-backend]
-       - scan-frontend:
-          requires: [build-frontend]
-       - deploy-infrastructure:
-          requires:
-            - scan-backend
-            - scan-frontend
-            - test-backend
-            - test-frontend
-       - configure-infrastructure:
-           requires: [deploy-infrastructure]
-      
-          
+  application_workflow:
+    jobs:
+      # - build-frontend
+      # - build-backend
+      # - test-frontend:
+      #     requires: [build-frontend]
+      # - test-backend:
+      #     requires: [build-backend]
+      # - scan-backend:
+      #     requires: [build-backend]
+      # - scan-frontend:
+      #     requires: [build-frontend]
+      # - deploy-infrastructure:
+          #  requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          #  filters:
+            # branches:
+              # only: [master]
+      # - configure-infrastructure:
+          # requires: [deploy-infrastructure]
+      # - run-migrations:
+          # requires: [configure-infrastructure]
+      # - deploy-frontend:
+          # requires: [run-migrations]
+      # - deploy-backend:
+          # requires: [run-migrations]
+      # - smoke-test:
+          # requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
+
+
+
+      # - notify_on_success:
+          # requires: 
+            # - build-frontend
+            # - build-backend
+            # - test-frontend
+            # - test-backend
+            # - scan-backend
+            # - scan-frontend
+            # - deploy-infrastructure
